---

- name: set fact force_install to no
  set_fact: force_install=no

- name: set fact force_install to yes
  set_fact: force_install=yes
  when: es_allow_downgrades

- name: Debian - Install apt-transport-https to support https APT downloads
  become: yes
  apt: name=apt-transport-https state=present

- name: Debian - Add Elasticsearch repository key
  become: yes
  apt_key:
    url: "{{ es_apt_key }}"
    state: present

- name: Debian - Add elasticsearch repository
  become: yes
  apt_repository: repo={{ item.repo }} state={{ item.state}}
  with_items:
    - { repo: "{{ es_apt_url_old }}", state: "absent" }
    - { repo: "{{ es_apt_url }}", state: "present" }

- name: Debian - Include versionlock
  import_tasks: elasticsearch-Debian-version-lock.yml
  when: es_version_lock

- name: Debian - Ensure elasticsearch is installed
  become: yes
  apt:
    name: "elasticsearch={{ es_version }}"
    state: present
    force: "{{ force_install }}"
    allow_unauthenticated: yes
    cache_valid_time: 86400
  register: debian_elasticsearch_install_from_repo
  notify: restart elasticsearch
  when: not ansible_check_mode
