- name: Set elastic cluster to join
  set_fact:
    elastic_servers: "{{ groups[service] }}"
  tags:
    - elastic_config
    - discovery_zen_minimum_master_nodes

- name: debug message elasticservers
  debug:
    msg: "{{ elastic_servers }}"

- debug:
    msg: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  with_items:
    - "{{ elastic_servers }}"


- name: debug message heapsize
  debug:
    msg: "{{ es_heap_size }}"
