- name: Set elastic cluster to join
  set_fact:
    elastic_servers: "{{ groups[service] }}"
  tags:
    - elastic_config
    - discovery_zen_minimum_master_nodes

- name: debug message elasticservers
  debug:
    msg: "{{ elastic_servers }}"

- name: test pipeline file
  template:
    src: testing.yml.j2
    dest: /tmp/test.yml
    owner: root
    group: root

- name: debug message heapsize
  debug:
    msg: "{{ es_heap_size }}"
