---
- name: Touch the same file
  file:
    path: /tmp/test
    state: touch
    mode: u+rw,g-wx,o-rwx

- name: Testing a host file
  lineinfile:
    dest: /tmp/test
    regexp: '^{{ ansible_default_ipv4.address }}'
    line: '{{ ansible_default_ipv4.address }} {{ fqdn }} {{ hostname }}'
    state: present
    backup: true
    unsafe_writes: true
  when: ansible_default_ipv4.address is defined
