---

- name: Get data disk from instance
  shell: |
    ls /dev/{{ disk_prefix }}* | grep -v {{ disk_prefix }}a | egrep -v '{{ disk_prefix }}b$' |  sed '/[09]$/d'
  register: discover_disk
  failed_when: False
  changed_when: False

- debug:
    msg: "Data disk: {{ discover_disk.stdout_lines }}"

- set_fact:
    disk: "{{ discover_disk.stdout_lines | join(',') }}"